/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.perpustakaanApps.app.view.admin;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.java.com.perpustakaanApps.app.controller.admin.AdminModel;
import main.java.com.perpustakaanApps.database.Koneksi;

public class KelolaPengguna extends javax.swing.JFrame {

    AdminModel admin = new AdminModel();
    public KelolaPengguna() {
        initComponents();
        load_data();
        
        
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
    }
    
    private void load_data()
    {
        Connection con=Koneksi.getConnection();
        Object header[]={"ID Pengguna","Nama Lengkap","Username","Password","No Telepon"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        TabelPengguna.setModel(data);
        String sql_data="SELECT * FROM user";
        try
        {
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql_data);
            while(rs.next())
            {
                String d1=rs.getString(1);
                String d2=rs.getString(2);
                String d3=rs.getString(3);
                String d4=rs.getString(4);
                String d5=rs.getString(5);
                
                
                
                
                String d[]={d1,d2,d3,d4,d5};
                data.addRow(d);
                
            }
        }
        catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
                          
    }
     public String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(password.getBytes());
            StringBuilder hexString = new StringBuilder();

            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
    
    private void update()
    {try
        {
            Connection con=Koneksi.getConnection();
            Statement st=con.createStatement();
           
            
            String sql_update="UPDATE user SET nama_lengkap='"+txtnamalengkap.getText()
                    +"',username='"+txtusername.getText()
                    +"',password='"+txtpassword.getText()
                    +"',no_telepon='"+txtnotelepon.getText()
                    +"'WHERE id='"+txtidpengguna.getText()+"'";
                    
            st.execute(sql_update);
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
        }
        catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
                          
    }
    
    private void delete()
    {
        try
        {
            Connection con=Koneksi.getConnection();
            Statement st=con.createStatement();
            String sql_delete="DELETE from user WHERE id='"+txtidpengguna.getText()+"'";
            st.executeUpdate(sql_delete);
            JOptionPane.showMessageDialog(null, "Data Berhasil DIhapus");
            
            
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
            
    
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidpengguna = new javax.swing.JTextField();
        txtnamalengkap = new javax.swing.JTextField();
        txtnotelepon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnTambah = new rojerusan.RSMaterialButtonRectangle();
        btnReset = new rojerusan.RSMaterialButtonRectangle();
        btnHapus = new rojerusan.RSMaterialButtonRectangle();
        btnEdit = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPengguna = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 176, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KELOLA PENGGUNA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 380, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Pengguna");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));

        txtusername.setBackground(new java.awt.Color(0, 176, 255));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setToolTipText("");
        txtusername.setBorder(null);
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Lengkap ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Telepon");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 190, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/perpustakaanApps/icons/undraw_Experts_re_i40h(1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 610, 340));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 410, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/com/perpustakaanApps/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel11.setText("BACK");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        txtidpengguna.setEditable(false);
        txtidpengguna.setBackground(new java.awt.Color(0, 176, 255));
        txtidpengguna.setForeground(new java.awt.Color(255, 255, 255));
        txtidpengguna.setToolTipText("");
        txtidpengguna.setBorder(null);
        txtidpengguna.setCaretColor(new java.awt.Color(255, 255, 255));
        txtidpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpenggunaActionPerformed(evt);
            }
        });
        jPanel1.add(txtidpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 400, 20));

        txtnamalengkap.setBackground(new java.awt.Color(0, 176, 255));
        txtnamalengkap.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtnamalengkap.setForeground(new java.awt.Color(255, 255, 255));
        txtnamalengkap.setToolTipText("");
        txtnamalengkap.setBorder(null);
        txtnamalengkap.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnamalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamalengkapActionPerformed(evt);
            }
        });
        jPanel1.add(txtnamalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, 20));

        txtnotelepon.setBackground(new java.awt.Color(0, 176, 255));
        txtnotelepon.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtnotelepon.setForeground(new java.awt.Color(255, 255, 255));
        txtnotelepon.setToolTipText("");
        txtnotelepon.setBorder(null);
        txtnotelepon.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnotelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoteleponActionPerformed(evt);
            }
        });
        jPanel1.add(txtnotelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 400, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 410, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 410, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 410, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 20));

        jTextField8.setBackground(new java.awt.Color(0, 176, 255));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setToolTipText("");
        jTextField8.setBorder(null);
        jTextField8.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 400, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 410, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("_______________________________________________________________________________");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 410, 20));

        txtpassword.setBackground(new java.awt.Color(0, 176, 255));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 400, -1));

        btnTambah.setBackground(new java.awt.Color(255, 255, 255));
        btnTambah.setForeground(new java.awt.Color(0, 176, 255));
        btnTambah.setText("TAMBAH\n");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 150, 40));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setForeground(new java.awt.Color(0, 176, 255));
        btnReset.setText("RESET");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 150, 40));

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setForeground(new java.awt.Color(0, 176, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 150, 40));

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setForeground(new java.awt.Color(0, 176, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 150, 40));

        TabelPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Lengkap", "Username", "Password", "No Telepon"
            }
        ));
        TabelPengguna.setColorBackgoundHead(new java.awt.Color(0, 176, 255));
        TabelPengguna.setColorBordeFilas(new java.awt.Color(0, 176, 255));
        TabelPengguna.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TabelPengguna.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        TabelPengguna.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        TabelPengguna.setFont(new java.awt.Font("Yu Gothic Light", 0, 25)); // NOI18N
        TabelPengguna.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        TabelPengguna.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        TabelPengguna.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        TabelPengguna.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TabelPengguna.setRowHeight(40);
        TabelPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPenggunaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelPengguna);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 600, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        setSize(new java.awt.Dimension(1200, 802));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoteleponActionPerformed

    private void txtnamalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamalengkapActionPerformed

    private void txtidpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpenggunaActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        String username = txtusername.getText();
        String password = String.valueOf(txtpassword.getPassword());
        String namalengkap = txtnamalengkap.getText();
        String notelepon = txtnotelepon.getText();

        if(namalengkap.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan Nama Lengkap");
        }

        else if(username.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan Username");
        }
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan Password");
        }

        else if(notelepon.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan Nomor Telepon");
        }
        else
        {
            PreparedStatement ps;
            ResultSet rs;
            String hashedPassword = hashPassword(password); // Hash password
            String query = "INSERT INTO `user`(`nama_lengkap`, `username`, `password`, `no_telepon`) VALUES (?,?,?,?)";
            try  {
                ps = Koneksi.getConnection().prepareStatement(query);

                ps.setString(1, namalengkap);
                ps.setString(2, username);
                ps.setString(3, hashedPassword);
                ps.setString(4, notelepon);

                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan !!!");
                    txtnamalengkap.setText("");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtnotelepon.setText("");
                    load_data();

                }

            } catch (SQLException ex) {
                Logger.getLogger(RegisterAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnTambahMouseClicked

    private void TabelPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPenggunaMouseClicked
        // TODO add your handling code here:
        int bar=TabelPengguna.getSelectedRow();
        String a=TabelPengguna.getValueAt(bar, 0).toString();
        String b=TabelPengguna.getValueAt(bar, 1).toString();
        String c=TabelPengguna.getValueAt(bar, 2).toString();
        String d=TabelPengguna.getValueAt(bar, 3).toString();
        String e=TabelPengguna.getValueAt(bar, 4).toString();

        txtidpengguna.setText(a);
        txtnamalengkap.setText(b);
        txtusername.setText(c);
        txtpassword.setText(d);
        txtnotelepon.setText(e);

        btnTambah.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);

    }//GEN-LAST:event_TabelPenggunaMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int update = JOptionPane.showOptionDialog(this,
            "Apakah Data akan Di Update? Update?",
            "Update Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(update==JOptionPane.YES_OPTION)
        {
            update();
            load_data();
            btnTambah.setEnabled(true);
            btnEdit.setEnabled(false);
            btnHapus.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showOptionDialog(this,
            "Apakah Data akan Di Hapus? Hapus?",
            "Hapus Data",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(delete==JOptionPane.YES_OPTION)
        {
            delete();
            load_data();
            btnTambah.setEnabled(true);
            btnEdit.setEnabled(false);
            btnHapus.setEnabled(false);
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(100);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        String username = admin.getUsername();
        DashboardAdmin dashboard = new DashboardAdmin();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        txtidpengguna.setText("");
        txtnamalengkap.setText("");
        txtusername.setText("");
        txtpassword.setText("");
        txtnotelepon.setText("");
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new KelolaPengguna().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro TabelPengguna;
    private rojerusan.RSMaterialButtonRectangle btnEdit;
    private rojerusan.RSMaterialButtonRectangle btnHapus;
    private rojerusan.RSMaterialButtonRectangle btnReset;
    private rojerusan.RSMaterialButtonRectangle btnTambah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtidpengguna;
    private javax.swing.JTextField txtnamalengkap;
    private javax.swing.JTextField txtnotelepon;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
